### ISSUE TITLE
get_field() not working in load_field filter when plugin is active

### ISSUE THREAD

**Issue by JakedUp** [Hube2/acf-reusable-field-group-field#11]
This is the weirdest scenario, but it only happens when this plugin is active. The field group doesn't even have to be in use -- just needs to be active.

```
// DYNAMIC FILTER CHOICES
function acf_dynamic_filters($field) {
  if (is_admin()) {
    $terms = get_field('filter_groups');
    // OTHER CODE ...
  }
  return $field;
}
add_filter('acf/load_field/name=filter_group', 'acf_dynamic_filters');
```

filter_group is a select dropdown and filter_groups is a taxonomy field.

When this plugin as active $terms = null -- when inactive, the value is correct.

**Comment by Hube2** [comment]
So, to understand this, it's the get_field() in the filter that's not working. The filter itself is being called normally.

**Comment by JakedUp** [comment]
Correct.

**Comment by Hube2** [comment]
So maybe I do need some more information.

I'm assuming that 'filter_group' is on the same post as 'filter_groups' since you're not supplying a post ID value.

Are these fields in the same field group?

Are you assigning the terms from `filter_groups` to the choices of 'filter_group'?
something like
```
foreach ($terms as $term) {
  $field['choices'][$term->term_id] = $term->name;
}
```

Also assuming that both fields are at the top level and neither is in a repeater of flex field and they are not fields used in any reusable field group setup since you say no reusable groups need to be in use.

Let me know if all of this sounds right.

~JH

**Comment by JakedUp** [comment]
Exactly!

```
// DYNAMIC FILTER CHOICES
function acf_dynamic_filters($field) {
  if (is_admin()) {
    $terms = get_field('filter_groups');
    if (!$terms) {
      $terms = array((object) array('name' => 'No Groups!'));
    }
    $field['choices'] = array();
    foreach ($terms as $term) {
      $field['choices'][$term->name] = $term->name;
    }
  }
  return $field;
}
add_filter('acf/load_field/name=filter_group', 'acf_dynamic_filters');
```

**Comment by Hube2** [comment]
I'm pretty sure this is an ACF wp_cache issue. Working on a solution.

**Comment by kokers** [comment]
Yeah, i think that too. Don't know much about how the wp cache is working.
If you need anymore informations or debugging or something just let me know
:o)

**Comment by Hube2** [comment]
So the issue was with the wp cache and it should now be working in the latest commit.

I use the function acf_get_field_gorups() and acf_get_fields() to get the existing field groups to see what needs to be rebuilt. This causes ACF to store the values returned from those functions into the WP cache.

To correct this issue I am now clearing all of ACF's cached values after I use these functions. To prevent this cache setting and clearing on every page load I am also storing what is returned from them in a local json file. This file is only deleted when a field group is created or updated so this will limit the cache clearing to one time after updates are made to field groups.

Let me know if you still see problems with this.

~JH

**Comment by JakedUp** [comment]
Thanks, I'll take a look!
