### ISSUE TITLE
Naming Issues

### ISSUE THREAD

**Issue by christianmagill** [Hube2/acf-reusable-field-group-field#17]
Love the idea behind this plugin, but I wonder if the naming issues could be resolved by treating the reusable field group more like a repeater field.

I often reuse field names such as "title" and "content" for components such as "accordions" and "tabs" to keep things consistent and easy to remember. However, it's usually not an issue because these fields are encapsulated in a repeater.

**Comment by Hube2** [comment]
The reason that it's built the way it's built is so that I did not need to build a lot of functionality beyond the copy process. 

The logic and how data is saved with a repeater field is far more complicated and I would not be able to use the built in ACF functions, more than likely I'd need to build a whole new set of function for saving, getting and looping through the rows. 

While I can understand that some might want it to work similar to a repeater, the extra complexity is not something that I will have the time to maintain.

**Comment by Hube2** [comment]
Just wanted to add, if Elliot decides to build some type of reusable groups directly into ACF I think it could most likely be made to work with the existing repeater field functionality. The problem with doing it as an add on is that it's not as easy to do. Making changes to the ACF code you can add logic to the functions for saving, getting an looping to deal with two types of fields using it. As an add on all of that logic and code would need to be duplicated and the functions would need to have different names.
