### ISSUE TITLE
Reusable fields don't display in flex/repeater when local JSON is enabled.

### ISSUE THREAD

**Issue by justinhines57** [Hube2/acf-reusable-field-group-field#21]
If an `acf-json` directory is present in the active theme, reusable fields in flexible content and repeater fields do not sure up on the edit screen.

**Comment by Hube2** [comment]
This should be corrected, running into more troubles with how ACF caches field groups and fields. Basically using this plugin is going to create additional hits on files if using local json in ACF and may mean additional DB requests if not using local json. There is no way for me to avoid this because I have to completely wipe the ACF cache if the local field group already exists.

**Comment by Hube2** [comment]
I have added a warning and suggestions about how to use this plugin to the readme.
