### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by kokers** [Hube2/acf-reusable-field-group-field#22]
OK, so your last comment about performance and stuff made me a bit worry, as the performance is very crucial for me. We often ship websites that are expanded on the go, so this means I need to rethink if I should use this plugin on some sites (but this just can't happen as this is the best addon for ACF so far).

can you please elaborate a bit more on where there will be significant performance hit? I saw comments in this issue https://github.com/Hube2/acf-reusable-field-group-field/issues/15 and your recommendation to not use it on production. I'm doing some testing with local acf-json, and can't really see an issue right now. Don't really see any extra queries (I'm using Query Monitor) . And now I'm a bit confused ;o)

For now I'm using reusanle field group as a "section settings". I have  layout with the flexible content that are simply a different section layouts (like e.q tabs, accordion, two columns, column + image, etc), and for each section there are exactly the same settings. So this saves me a lot of trouble when it comes to maintaining those settings. So I'm thinking that maybe in this simple case there won't be a performance issue and that's why I don't see problems right now?

On a side note, I don't know ACF code, I'm sure you are more familiar with it, but what you think about hooking this rebuild of ACF fields in the prepare_field_group_for_export hook? I noticed that just before saving json file there is function acf_prepare_field_group_for_export called and there is this:

	// filter for 3rd party customization
	$field_group = apply_filters('acf/prepare_field_group_for_export', $field_group);

so I'm wondering if we could add this rebuild here so that instead of this http://pastebin.com/wq13Ys7m we would have already rebuild field? Don't know what implications we would have here. One that I can think of would be that after that, changing reusable field group, would require to re-save all other jsons.

**Comment by Hube2** [comment]
First, thank you for saying this is the best ACF add on so far. I actually only started building this to see if I could and did not have any idea that it would end up as popular as it has.

Basically, I need to look at the field groups after ACF is finished loading them on the `acf/include_fields` hook. 999 is probably a higher priority than needed, but it needs to be higher than when the ACF function runs. This is the only way that I can be sure that all of the groups from the DB and local JSON are loaded in order to start looking for reusable fields and rebuilding them. When ACF loads field groups each group that's loaded and each field that's loaded is stored in WP cache. 

Originally I tried to selectively delete only the cached groups and fields that needed to be rebuilt, but somewhere along the line I was always missing something, or perhaps I'm unable to completely figure out what the cache key needs to be. Most of the problems with this has to do with the Local JSON feature of ACF.

The way ACF works, if I don't delete the cache for a group or field properly then the next time any function gets the group or field it uses the cached version and ignores any changes that were made to it.

It seemed that no matter what I tried I was always missing something, and the local JSON files from ACF were giving me the most trouble. So what I'm doing now is just deleting the entire 'acf' group from the wp cache.

To be 100% honest, I don't know if there will be a large performance issue or not. I have not run any tests to see what the actual effect on the site is. I am assuming that there will be some decrease in performance because clearing the cache means that whatever was done to load a field group or field needs to be redone by ACF the next time the field or group is needed. I would love to have some actual numbers and know for sure. I also tend to err of the side of caution and my language may be stronger than it needs to be.

I will look at it some more and see if there's a better way to do this. Maybe there's a way that I can rebuild individual fields when they are loaded instead of rebuilding the entire groups. I did think of this originally, and the plugin that I looked at that started me down the path of working on this in the first place did it that way, but there were some serious problems with duplicate field keys in reused fields in that plugin which is why I went down the path of rebuilding the entire group. It was the only way I could think of the be sure that I had the correct parent field key and also add the ability to remove the key prefixing for those that understood when it could be removed. I'm not sure that it's possible to do it per field because of the duplicate field key issue.

I will also try to find some more time to do a little more testing to see if I can successfully delete only what's needed from the cache rather than deleting everything.

Another possibility that I just thought of would be to load the local JSON field groups created by this plugin early, before ACF loads .... ah, that would work. Look for the field groups, if there are local JSON files load them and don't do the rebuilding at all. Then the only time that the field groups would be rebuilt would be when there is a change in the existing groups which causes this plugin to delete it's local JSON versions. The only problem I can see with this is that I will have no ability to detect if a theme's local JSON file was changed and it would mean that if someone alters a field group in a file that they would be required to go to the ACF group admin and update at least one field group in order to trigger the deletion of the local JSON files for this plugin.

What do you think about this last idea?

**Comment by kokers** [comment]
This is the only functionality I am missing in the ACF core. I'm sure other people who care about DRY (or at least ease of expanding/maintaining) are too. That's why this is a gold mine :o))

Ok, so with the last idea this https://www.advancedcustomfields.com/resources/synchronized-json/ will stop working? Never used it. I actually tried to cheat and make some "reusable" with php export but it's just impossible to maintain if there are changes needed later.  But anyway, maybe we could use some constance like "REBUILD_REUSABLE,true" or something in functions that would trigger the rebuild. Cause if someone already is modifying files, adding a temporality variable shouldn't be a problem. Or something similar to this, as I'm not sure this would work. But other then that, from the sound of that it could work. 

There is one thing I can think of without enough knowledge of source code - will there be any issues with fields created by third party plugins in that scenario? this is the only thing right now i can think of.

**Comment by Hube2** [comment]
The standard local json files would not stop working.

The way the local json works in ACF is the it loads local JSON files before it loads field groups from the DB, and ACF will only add a local group it the group does not already exist.

Anything that alters a field group in ACF triggers this plugin to delete its local json files, so updating, or syncing, or even moving a field group to trash will trigger the deletion.

This would be the sequence of events that I'm thinking about.

1) This plugin looks to see if it has local JSON files. If it does the field groups in those files are added. If there are local files then set a flag to say there's no need to go through the rebuilding process.

2) ACF will check for other local JSON files as normal and add those. Any groups (group keys) in these files that have already been added by will be skipped because acf_local will skip them if they already exist.

4) ACF loads field groups from the database. 

5) The rebuild process is triggered in this plugin. 

If the flag is set then this is aborted. 

If not aborted then field groups are rebuilt and the ACF group and field cache is cleared as necessary. The new field groups are saved as local JSON files to this does not need to happen again until some change is detected and the files are deleted.

6) Field groups defined in code by other devs. These may be loaded any time after 1 happens and before 5 happens. Exact timing depends on the priority they set. will set the priority of step 1 to -1 and the priority of 5 is set to 999, which is the best I can do to ensure third party field groups get caught as well. Most devs don't change the priority from the default of 10 so it shouldn't be a problem.

**Comment by kokers** [comment]
Yes, this sounds like a great idea. I cant think of anything right now that could go wrong. If you'll have anything to test let me know and I'd be happy to do it :o))

**Comment by Hube2** [comment]
I'll probably upload something today. Your question was a good one and it made me think about the order that things are happening. I honestly don't see anything that would stop this from working and fix the performance issue, but I'll  have to test it to know for sure.

**Comment by kokers** [comment]
Awesome :o) Thanks a lot!

**Comment by Hube2** [comment]
For anyone that can, if you can test this. I have done some testing myself and it appears to be working. Once I'm sure there aren't any problems I'll remove the warning in the readme.

**Comment by kokers** [comment]
Ok, I've tested it and I even played with this sync and didn;t see any issues. 
I will be working this weekend and using this, so I will let you know if anything comes up. For now looking great! :o))))

**Comment by kokers** [comment]
Everything works great :o) didn't had any issues or performance problems. Thanks a lot Hube! I think we can safely close this one :o)
