### ISSUE TITLE
Lose of mapping after Import

### ISSUE THREAD

**Issue by stagfoo** [Hube2/acf-reusable-field-group-field#27]
firstly this is super awesome time saver i love it. 
we have moved some reusable files from 1 website to another all our reusable fields are blank inside the page.
![selection_165](https://cloud.githubusercontent.com/assets/2702690/15955714/d118b3ac-2f26-11e6-81d3-e199dd40ddf3.png)
I really love this plugin and anything i can help with to fix this import issue im happy to help.

Perhaps the import gives new ids which are different from the relations stored in the plugin acf?

**Comment by Hube2** [comment]
I'm not sure I understand the problem. If you've imported ACF fields then this plugin should rebuild any reusable fields the first time they are needed and if the ACF fields have the same names and field keys then the reusable fields on the new site will have the same names and field keys.

Please outline the process you used to export fields and data from one site and into the other.

**Comment by stagfoo** [comment]
I used ACF default export to create a json file. I then imported that into the new website which created the acf fields under acf correctly all good there but, the reusable fields don't return any fields when i go to use them under the edit screen. eg card having not fields in the picture above.

**Comment by Hube2** [comment]
I'm pretty sure I know what's happening here. Importing into ACF does not cause the cache on this plugin to clear. The reason is that if this plugin tries to generate fields when on the ACF admin pages that it cause other issues. After importing fields you need to edit any field group, you don't need to change anything, you just need to save a field group which will cause this plugin to clear its cache and regenerate the field groups. I will look into ACF and see if there's any hooks in the import that I can use to cause trigger the clearing of the cache.

**Comment by Hube2** [comment]
I think the update should fix the issue.

**Comment by stagfoo** [comment]
Hi Hube2, 
Sorry i didnt get back to you, that's correct we cleared the json in the plugin and it regenrated the links and fixes the issue :smile: ill get the latest verison now. This really is a great plugin.
